/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteLayoutRouteImport } from './routes/_siteLayout'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as SiteLayoutIndexRouteImport } from './routes/_siteLayout/index'
import { Route as SiteLayoutRegisterRouteImport } from './routes/_siteLayout/register'
import { Route as SiteLayoutLoginRouteImport } from './routes/_siteLayout/login'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const SiteLayoutRoute = SiteLayoutRouteImport.update({
  id: '/_siteLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteLayoutIndexRoute = SiteLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteLayoutRoute,
} as any)
const SiteLayoutRegisterRoute = SiteLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => SiteLayoutRoute,
} as any)
const SiteLayoutLoginRoute = SiteLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SiteLayoutRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteLayoutIndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/login': typeof SiteLayoutLoginRoute
  '/register': typeof SiteLayoutRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteLayoutIndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/login': typeof SiteLayoutLoginRoute
  '/register': typeof SiteLayoutRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_siteLayout': typeof SiteLayoutRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_siteLayout/login': typeof SiteLayoutLoginRoute
  '/_siteLayout/register': typeof SiteLayoutRegisterRoute
  '/_siteLayout/': typeof SiteLayoutIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/_protected'
    | '/_siteLayout'
    | '/_protected/dashboard'
    | '/_siteLayout/login'
    | '/_siteLayout/register'
    | '/_siteLayout/'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SiteLayoutRoute: typeof SiteLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_siteLayout': {
      id: '/_siteLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_siteLayout/': {
      id: '/_siteLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteLayoutIndexRouteImport
      parentRoute: typeof SiteLayoutRoute
    }
    '/_siteLayout/register': {
      id: '/_siteLayout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof SiteLayoutRegisterRouteImport
      parentRoute: typeof SiteLayoutRoute
    }
    '/_siteLayout/login': {
      id: '/_siteLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SiteLayoutLoginRouteImport
      parentRoute: typeof SiteLayoutRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface SiteLayoutRouteChildren {
  SiteLayoutLoginRoute: typeof SiteLayoutLoginRoute
  SiteLayoutRegisterRoute: typeof SiteLayoutRegisterRoute
  SiteLayoutIndexRoute: typeof SiteLayoutIndexRoute
}

const SiteLayoutRouteChildren: SiteLayoutRouteChildren = {
  SiteLayoutLoginRoute: SiteLayoutLoginRoute,
  SiteLayoutRegisterRoute: SiteLayoutRegisterRoute,
  SiteLayoutIndexRoute: SiteLayoutIndexRoute,
}

const SiteLayoutRouteWithChildren = SiteLayoutRoute._addFileChildren(
  SiteLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  SiteLayoutRoute: SiteLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
