name: Lint

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

env:
  FORCE_COLOR: 3
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup
        uses: ./configs/github/setup

      - name: Copy env
        run: cp .env.example .env

      - name: Lint
        run: pnpm lint && pnpm lint:ws

      - name: Typecheck
        run: pnpm typecheck

      - name: Format
        run: pnpm format
